"""Generate a tax filing cheat-sheet PDF organized by T1 line number."""

from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)


def generate_cheat_sheet(filepath: str, tax_year: int, summary: dict,
                         estimate: dict, deadlines: list = None):
    """Generate a tax filing cheat-sheet PDF.

    filepath: where to save the PDF
    tax_year: the tax year being summarized (e.g. 2024)
    summary: output from get_summary()
    estimate: output from calculate_estimated_tax()
    deadlines: list of deadline dicts (optional)
    """
    doc = SimpleDocTemplate(
        filepath, pagesize=letter,
        leftMargin=0.6*inch, rightMargin=0.6*inch,
        topMargin=0.6*inch, bottomMargin=0.6*inch,
    )

    styles = getSampleStyleSheet()
    story = []

    # ── Custom Styles ──
    title_style = ParagraphStyle(
        "title", parent=styles["Title"],
        fontSize=20, textColor=colors.HexColor("#0f3460"),
        spaceAfter=8, alignment=0,
    )
    subtitle_style = ParagraphStyle(
        "subtitle", parent=styles["Normal"],
        fontSize=11, textColor=colors.HexColor("#666666"),
        spaceAfter=16,
    )
    section_style = ParagraphStyle(
        "section", parent=styles["Heading2"],
        fontSize=14, textColor=colors.HexColor("#0f3460"),
        spaceBefore=14, spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "body", parent=styles["Normal"],
        fontSize=10, spaceAfter=4,
    )
    note_style = ParagraphStyle(
        "note", parent=styles["Normal"],
        fontSize=9, textColor=colors.HexColor("#888888"),
        spaceAfter=12, leading=11,
    )

    # ── Header ──
    story.append(Paragraph(f"Tax Filing Cheat Sheet — {tax_year}", title_style))
    story.append(Paragraph(
        f"Generated by TaxKing AI on {datetime.now().strftime('%B %d, %Y')}",
        subtitle_style,
    ))

    # ── Refund / Owing Box ──
    refund = estimate.get("refund_or_owing", 0)
    is_refund = estimate.get("is_refund", True)
    label = "Estimated Refund" if is_refund else "Estimated Amount Owing"
    amount = abs(refund)
    color_hex = "#2ecc71" if is_refund else "#e74c3c"

    refund_box = Table(
        [[
            Paragraph(f"<b>{label}</b>", ParagraphStyle(
                "rbox", fontSize=14, textColor=colors.white)),
            Paragraph(
                f"<b>${amount:,.2f}</b>",
                ParagraphStyle("rbox2", fontSize=18, textColor=colors.white, alignment=2),
            ),
        ]],
        colWidths=[3.5*inch, 3.5*inch],
    )
    refund_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(color_hex)),
        ("PADDING", (0, 0), (-1, -1), 12),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(refund_box)
    story.append(Spacer(1, 12))

    story.append(Paragraph(
        f"<i>Province used: {estimate.get('province_name', 'Ontario')}. "
        f"This is an estimate using 2024 brackets — actual amount may differ.</i>",
        note_style,
    ))

    # ── Tax Summary Breakdown ──
    story.append(Paragraph("Tax Calculation Summary", section_style))

    breakdown_data = [
        ["Item", "Amount"],
        ["Total Income (gross)", f"${estimate.get('gross_income', 0):,.2f}"],
        ["+ Dividend gross-up (38%)", f"${estimate.get('gross_up_addition', 0):,.2f}"],
        ["- Capital gains adjustment (50% inclusion)",
         f"${estimate.get('capital_gains_adjustment', 0):,.2f}"],
        ["- Total Deductions (RRSP, RPP, union)", f"-${estimate.get('total_deductions', 0):,.2f}"],
        ["= Taxable Income", f"${estimate.get('taxable_income', 0):,.2f}"],
        ["", ""],
        ["Federal Tax (after credits)", f"${estimate.get('federal_tax', 0):,.2f}"],
        ["Provincial Tax (after credits)", f"${estimate.get('provincial_tax', 0):,.2f}"],
        ["Self-Employment CPP", f"${estimate.get('se_cpp_owing', 0):,.2f}"],
        ["Total Tax Owing", f"${estimate.get('total_tax', 0):,.2f}"],
        ["- Tax Already Deducted at Source", f"-${estimate.get('tax_already_paid', 0):,.2f}"],
        [label, f"${amount:,.2f}"],
    ]

    table = Table(breakdown_data, colWidths=[4.5*inch, 2*inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f3460")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor(color_hex)),
        ("TEXTCOLOR", (0, -1), (-1, -1), colors.white),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
        ("PADDING", (0, 0), (-1, -1), 6),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
    ]))
    story.append(table)
    story.append(Spacer(1, 16))

    # ── Marginal Rates ──
    mr_fed = estimate.get("marginal_rate_federal", 0) * 100
    mr_prov = estimate.get("marginal_rate_provincial", 0) * 100
    story.append(Paragraph(
        f"<b>Marginal tax rate:</b> {mr_fed + mr_prov:.1f}% "
        f"(federal {mr_fed:.1f}% + provincial {mr_prov:.1f}%)",
        body_style,
    ))
    story.append(Spacer(1, 8))

    # ── T1 Line-by-Line ──
    story.append(PageBreak())
    story.append(Paragraph("T1 Line-by-Line Cheat Sheet", title_style))
    story.append(Paragraph(
        "Type these numbers into the corresponding T1 lines in your tax software "
        "(Wealthsimple Tax, TurboTax, StudioTax, UFile, etc.). Lines with $0 can usually be skipped.",
        note_style,
    ))

    # Compute the derived values
    grossed_div = summary.get("total_eligible_dividends", 0) * 1.38
    cap_gains_taxable = summary.get("total_capital_gains", 0) * 0.5

    t1_lines = [
        ("10100", "Employment income", summary.get("total_employment_income", 0)),
        ("11500", "Other pensions / superannuation", summary.get("total_pension_income", 0)),
        ("11900", "Employment Insurance benefits", summary.get("total_ei_benefits", 0)),
        ("12000", "Taxable amount of eligible dividends (grossed up 38%)", grossed_div),
        ("12100", "Interest and other investment income", summary.get("total_interest_income", 0)),
        ("12700", "Taxable capital gains (50% inclusion)", cap_gains_taxable),
        ("12900", "RRSP income (T4RSP withdrawals)", summary.get("total_rrsp_withdrawals", 0)),
        ("13000", "Other income", summary.get("total_other_income", 0)),
        ("13700", "Self-employment income", summary.get("total_self_employment", 0)),
        ("15000", "Total income", estimate.get("adjusted_income", 0)),
        ("", "", ""),
        ("20700", "Registered Pension Plan deduction", summary.get("total_rpp_contributions", 0)),
        ("20800", "RRSP deduction", summary.get("total_rrsp_contributions", 0)),
        ("21200", "Union, professional, or like dues", summary.get("total_union_dues", 0)),
        ("23600", "Net income (after deductions)", estimate.get("taxable_income", 0)),
        ("", "", ""),
        ("30800", "CPP/QPP contributions through employment", summary.get("total_cpp_contributions", 0)),
        ("31200", "EI premiums through employment", summary.get("total_ei_premiums", 0)),
        ("32300", "Tuition amount (T2202)", summary.get("total_tuition", 0)),
        ("40500", "Foreign tax credit (US tax withheld)", summary.get("total_us_tax_withheld", 0)),
        ("43700", "Total income tax deducted (T4 Box 22)", summary.get("total_income_tax_deducted", 0)),
    ]

    line_data = [["Line", "Description", "Amount"]]
    for line, desc, val in t1_lines:
        if line == "":
            line_data.append(["", "", ""])
        else:
            amt = f"${val:,.2f}" if val and val > 0 else "—"
            line_data.append([f"Line {line}", desc, amt])

    line_table = Table(line_data, colWidths=[1*inch, 4.5*inch, 1.5*inch])
    line_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f3460")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
        ("ALIGN", (2, 0), (2, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
        ("PADDING", (0, 0), (-1, -1), 5),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(line_table)
    story.append(Spacer(1, 16))

    # ── Slip Inventory ──
    story.append(PageBreak())
    story.append(Paragraph("Slip Inventory", section_style))
    story.append(Paragraph(
        "All tax slips currently in your TaxKing AI records. "
        "Check this list against what your issuers have sent to make sure nothing is missing.",
        note_style,
    ))

    slip_data = [["Form", "Issuer / Description", "Key Amount"]]
    # We'd need access to the docs list — pass the summary doesn't include that directly.
    # The caller can pass extra info if needed.
    # For now, fall back to showing the counts.
    counts = [
        ("T4 slips", summary.get("t4_count", 0)),
        ("T5 slips", summary.get("t5_count", 0)),
        ("Other Canadian slips", summary.get("canadian_other_count", 0)),
        ("US tax forms (cross-border)", summary.get("us_form_count", 0)),
    ]
    for name, count in counts:
        if count > 0:
            slip_data.append([name, f"{count} slip(s) on file", "—"])

    if len(slip_data) > 1:
        slip_table = Table(slip_data, colWidths=[1.8*inch, 3.7*inch, 1.5*inch])
        slip_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f3460")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
        ]))
        story.append(slip_table)
        story.append(Spacer(1, 12))

    # ── Deadlines ──
    if deadlines:
        story.append(Paragraph("Important Deadlines", section_style))
        dl_data = [["Deadline", "Date", "Days Until"]]
        for d in deadlines:
            days = d["days_until"]
            if days < 0:
                days_str = f"{abs(days)} days ago"
            elif days == 0:
                days_str = "TODAY"
            else:
                days_str = f"in {days} days"
            dl_data.append([
                d["name"],
                d["date"].strftime("%B %d, %Y"),
                days_str,
            ])

        dl_table = Table(dl_data, colWidths=[3*inch, 2*inch, 2*inch])
        dl_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f3460")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
        ]))
        story.append(dl_table)
        story.append(Spacer(1, 12))

    # ── Footer ──
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>This cheat sheet is an estimate generated by TaxKing AI based on the "
        "slips you've uploaded. It does not constitute professional tax advice. "
        "Always verify your return with a tax professional or by using CRA-certified "
        "tax software before filing.</i>",
        note_style,
    ))

    doc.build(story)
    return filepath
